const ActionTypes = {
  SHOW_POST: "SHOW_POST",
  CURRENT_USER: "CURRENT_USER",
  POST_DATA: "POST_DATA",
  POST_PATH: "POST_PATH",
  PROFILE_DATA: "PROFILE_DATA",
  COMMENT_DATA: "COMMENT_DATA",
  NULL_COMMENTS: "NULL_COMMENTS",
  USER_LIST: "USER_LIST",
  MESSEGES: "MESSEGES",
  USER_NULL: "USER_NULL",
  MESSEGES_DATA: "MESSEGES_DATA",
}

export default ActionTypes